### ISSUE TITLE
Firefox extension could not be found

### ISSUE THREAD

**Issue by jellevervloessem** [rajyraman/Level-up-for-Dynamics-CRM-365-Firefox#1]
Hi @rajyraman ,

I'm reading a lot of good stuff about the latest firefox updates (privacy, performance, no snoopware).
I would give it a try, so how is it possible to install the Level-up-for-Dynamics-CRM-365 to FireFox?
In the Readme file there is no url provided and I cannot find the extenion.

Thanks,
J.

**Comment by rajyraman** [comment]
I submitted the extension and got rejected couple of times. See review below
![image](https://user-images.githubusercontent.com/5035266/26858681-09627240-4b76-11e7-8f22-f6c35e4121b4.png)

The source code is almost same as the Chrome one. So, I do not know why this is rejected constantly.

You can still sideload the extension as described in https://blog.mozilla.org/addons/2015/12/23/loading-temporary-add-ons/ from the addon sourcecode location. But, it is not same as developer mode in Chrome, as the extension is removed every time after a browser restart.

**Comment by chaoscreater** [comment]
To install this in Firefox as a permanent extension, there's a workaround. Install Chrome Store Foxified in Firefox v56 (any version above this will not work as of this writing). Then, browse to the Chrome extension in the Chrome store and add it to Firefix (it will convert for you and upload the extension to your Firefox developer account, which you'll need to create). Once done, follow this guide here:
https://github.com/Noitidart/Chrome-Store-Foxified/issues/113
